### ISSUE TITLE
Works with Raspberry pi4?

### ISSUE THREAD

**Issue by thefantas** [mcauser/micropython-ys-irtm#1]
Works with Raspberry pi4?

**Comment by mcauser** [comment]
It's a 5V UART IR module, which means you'll need to use the 3V-5V level shifter to work with the Raspi 3V UARTs.
To make it work on _big python_ on the Raspi, should only require small modifications, eg. swap the machine/uart for smbus.

I don't have a Pi handy, but next time I do, I'll port the code across.

**Comment by thefantas** [comment]
Hello, RPi4 has output voltage of 3.3V and 5V, I think you are confusing with a zero RPI (which only have 3.3V).
I'll be waiting for your input :).

**Comment by thefantas** [comment]
Hi, I think I'm confused... 
According to the [image](url
![imagen](https://user-images.githubusercontent.com/2816602/100772766-b2423c00-3408-11eb-8ce3-3f13aa15e629.png)
)..  
That board works at 5V... and you use converter... Can't connect directly to Raspberry? I put it in directly and I can't get it to work.

**Comment by mcauser** [comment]
https://www.raspberrypi.org/documentation/configuration/uart.md
> All UARTs on the Raspberry Pi are 3.3V only - damage will occur if they are connected to 5V systems. An adaptor can be used to connect to 5V systems. Alternatively, low-cost USB to 3.3V serial adaptors are available from various third parties.

If you replace the TinyPICO above with a Raspberry Pi 4, you will still need to power the YS-IRTM with 5V (thats what the onboard mcu requires), but that red board in the middle is required to convert the RXD and TXD from 5V TTL level down to a safe 3.3V level so you don't burn the Pi's UART pins.

Yes, the Pi4 has both 3 and 5V outputs, but it's the UART signal pins you have to be careful with. They are not 5V tolerant.

If you don't have a logic level converter, you could use a voltage divider circuit (just a few resistors) to drop the TXD down to a safe level. Not sure if the YS-IRTM works with a 3V RXD input though.
